name: CI
on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-13

    steps:
    - uses: actions/checkout@v4

    - uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: 14.3.1
        
    - name: Install Ruby
      run: bundle install
      
    - name: Cache CocoaPods libraries
      uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
      
    - name: Install Cocoapods
      run: pod install
      
    - name: Run tests
      run: make test
